### ISSUE TITLE
Example with `and()` operator needed.

### ISSUE THREAD

**Issue by msangel** [petitparser/java-petitparser#34]
Have no clue how to use it and no examples anywhere in java. 
All what I found is this test case:
```java
Parser parser = of('a').and();
assertSuccess(parser, "a", 'a', 0);
assertFailure(parser, "b", "'a' expected");
assertFailure(parser, "");
```
But this does not show how to combine different rules using this operator.
For example, I know "\n" is both `whitespace()` and "\n", how can I test this using this operator?
```java
of("\n").and() ????? whitespace()
```

**Comment by renggli** [comment]
The `and()` operator behaves like a positive lookahead in regular expressions: it parses and returns the input, but does not consume it. This means the next parser will start at the beginning again.

In your case

```java
of("\n").and().seq(whitespace())
```

will return a list with two times the same `"\n"` character, once from the `of("\n").and()` and once from the `whitespace()`. That said, the example doesn't make much sense because `of("\n")` is a subset of `whitespace()`, so the operator is not necessary.

An actual example is the Smalltalk grammar given in https://github.com/petitparser/java-petitparser/blob/45ffbd197cfda5f0dfb043ecfa0da2619355bbec/petitparser-smalltalk/src/main/java/org/petitparser/grammar/smalltalk/SmalltalkDefinition.java#L124. This parser will accept constructs that ends in "|" or "]", but if it is a "]" it does not consume it and let it be consumed by the caller.

**Comment by msangel** [comment]
Yes, I saw Smalltalk samples, but I am too yank and cannot read that.
The sample was simplified. 
My real-world case is(if to follow logic above):
```java
Parser space = of("\n").not().seq(whitespace());
Parser parser = space.star();
```
So it ate all the whitespace except the new line character. Is that true?

**Comment by renggli** [comment]
Yes, that's correct.
