### ISSUE TITLE
nonOf Parser Bug?

### ISSUE THREAD

**Issue by webITSol** [petitparser/java-petitparser#49]
```
class NoneOfTest {
    @Test
    void testNoneOfTrim() {
        Parser noneOfParser = CharacterParser.noneOf("xyz").plus().flatten();
        Parser noneOfTrimParser = noneOfParser.trim();

        assertEquals("abc", noneOfParser.parse("abc").get());
        assertEquals(" abc ", noneOfParser.parse(" abc ").get());
        assertEquals("abc", noneOfTrimParser.parse("abc").get());
        assertEquals("abc", noneOfTrimParser.parse(" abc ").get()); // fails
    }
}
```

Last assert fails. Is that intended?

**Comment by renggli** [comment]
This is expected: The resulting string for `noneOfTrimParser.parse(" abc ").get()` is `"abc "` (with a whitespace at the end). The reason is that `noneOf("xyz")` accepts whitespace, and `noneOf("xyz").plus()` consumes as much input as possible, so `noneOf("xyz").plus().flatten()` will return `"abc "`, and `noneOf("xyz").plus().flatten().trim()` will have nothing more to consume at the end (the trim parser does not affect the returned result, it only affects what is ignored before and after its inner parser).

You can fix this by including whitespace in the character parser `noneOf("xyz \n\r")`, however this will break your second assertion. Not sure what the desired behaviour is?

**Comment by bpieber** [comment]
Hi Lukas,

Thanks for the super-fast response!

Bernhard Pieber

**Comment by webITSol** [comment]
Yes, thank you! We are using your framework to implement a validation framework based on a user defined grammar, e.g. if some xmlnode contains certain value then return error.
At this particular point we want to parse a string that may contain any char except the ones from the noneOf argument, and sometimes the value is wrapped into a "'" which we want to trim.
I think we will be able to implement a proper solution now. Thanks again!
